import json
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)

# 1. 35 CROP CATALOG (plant_database.json)
PLANT_DATABASE = {
  "Solanaceae": [
    {"id": "sol_tomato", "name": "Tomato", "scientific_name": "Solanum lycopersicum", "status": "AI Detection Available", "ai_supported": True, "description": "High-value commercial crop. Full AI diagnosis active for 10 conditions."},
    {"id": "sol_potato", "name": "Potato", "scientific_name": "Solanum tuberosum", "status": "AI Detection Available", "ai_supported": True, "description": "Staple tuber crop. Full AI diagnosis active for Early Blight, Late Blight, and Healthy Foliage."},
    {"id": "sol_capsicum", "name": "Capsicum / Bell Pepper", "scientific_name": "Capsicum annuum", "status": "AI Detection Available", "ai_supported": True, "description": "Sweet pepper crop. Full AI diagnosis active for Bacterial Spot and Healthy Foliage."},
    {"id": "sol_brinjal", "name": "Brinjal / Eggplant", "scientific_name": "Solanum melongena", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "sol_chilli", "name": "Chilli", "scientific_name": "Capsicum frutescens", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."}
  ],
  "Cucurbit Vegetables": [
    {"id": "cuc_pumpkin", "name": "Pumpkin", "scientific_name": "Cucurbita moschata", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "cuc_cucumber", "name": "Cucumber", "scientific_name": "Cucumis sativus", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "cuc_bottle_gourd", "name": "Bottle Gourd / Lauki", "scientific_name": "Lagenaria siceraria", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "cuc_bitter_gourd", "name": "Bitter Gourd / Karela", "scientific_name": "Momordica charantia", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "cuc_ridge_gourd", "name": "Ridge Gourd / Turai", "scientific_name": "Luffa acutangula", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "cuc_sponge_gourd", "name": "Sponge Gourd / Gilki", "scientific_name": "Luffa aegyptiaca", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "cuc_pointed_gourd", "name": "Pointed Gourd / Parwal", "scientific_name": "Trichosanthes dioica", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "cuc_ash_gourd", "name": "Ash Gourd / Petha", "scientific_name": "Benincasa hispida", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "cuc_zucchini", "name": "Zucchini", "scientific_name": "Cucurbita pepo", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "cuc_snake_gourd", "name": "Snake Gourd / Chichinda", "scientific_name": "Trichosanthes cucumerina", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "cuc_ivy_gourd", "name": "Ivy Gourd / Kundru", "scientific_name": "Coccinia grandis", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."}
  ],
  "Common Indian Vegetables": [
    {"id": "com_okra", "name": "Okra / Lady Finger / Bhindi", "scientific_name": "Abelmoschus esculentus", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "com_french_bean", "name": "French Bean", "scientific_name": "Phaseolus vulgaris", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "com_green_bean", "name": "Green Bean", "scientific_name": "Phaseolus vulgaris var.", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "com_peas", "name": "Peas / Matar", "scientific_name": "Pisum sativum", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "com_sweet_corn", "name": "Sweet Corn", "scientific_name": "Zea mays var. saccharata", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "com_carrot", "name": "Carrot", "scientific_name": "Daucus carota", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "com_radish", "name": "Radish / Mooli", "scientific_name": "Raphanus sativus", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "com_beetroot", "name": "Beetroot", "scientific_name": "Beta vulgaris", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "com_turnip", "name": "Turnip / Shalgam", "scientific_name": "Brassica rapa subsp. rapa", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."}
  ],
  "Cole Vegetables": [
    {"id": "col_cabbage", "name": "Cabbage", "scientific_name": "Brassica oleracea var. capitata", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "col_cauliflower", "name": "Cauliflower", "scientific_name": "Brassica oleracea var. botrytis", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "col_broccoli", "name": "Broccoli", "scientific_name": "Brassica oleracea var. italica", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."}
  ],
  "Leafy Vegetables": [
    {"id": "lea_spinach", "name": "Spinach / Palak", "scientific_name": "Spinacia oleracea", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "lea_fenugreek", "name": "Fenugreek / Methi", "scientific_name": "Trigonella foenum-graecum", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "lea_coriander", "name": "Coriander / Dhaniya", "scientific_name": "Coriandrum sativum", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "lea_lettuce", "name": "Lettuce", "scientific_name": "Lactuca sativa", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "lea_amaranth", "name": "Amaranth / Chaulai", "scientific_name": "Amaranthus cruentus", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."}
  ],
  "Bulb Vegetables": [
    {"id": "bul_onion", "name": "Onion", "scientific_name": "Allium cepa", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."},
    {"id": "bul_garlic", "name": "Garlic", "scientific_name": "Allium sativum", "status": "Knowledge Available / Training Planned", "ai_supported": False, "description": "Crop information available — AI leaf disease detection is being calibrated."}
  ]
}

# 2. COMPLETE DEEP PATHOLOGY PROFILES ACROSS ALL 35 CROPS (diseases.json)
DISEASE_DATABASE = {
  # --- SOLANACEAE ---
  "Pepper Bell Bacterial Spot": {
    "crop": "Capsicum / Bell Pepper",
    "scientific_crop": "Capsicum annuum",
    "category": "Bacterial Infection",
    "pathogen": "Xanthomonas campestris pv. vesicatoria",
    "severity": "High",
    "status": "AI Detection Available",
    "badge": "status-danger",
    "overview": "Causes water-soaked angular leaf spots, severe defoliation, and raised brown scabs on pepper pods.",
    "etiology": "Gram-negative rod bacterium with a single polar flagellum. Transmitted via seed, rain splash, and mechanical handling in wet canopies.",
    "symptoms": "• Foliar: Small (1-3 mm) water-soaked lesions turning dark brown with yellow chlorotic halos.\n• Fruit: Blister-like eruptions rupturing into rough, scabby craters (4-8 mm).",
    "causes": "Extended foliar wetness (> 4 hours), high humidity (> 80%), daytime temperatures 24-32°C.",
    "chemical_treatment": "Copper Hydroxide (53.8% DF @ 2.0-2.5 g/L) + Mancozeb (75% WP @ 2.0 g/L). PHI: 3 days.",
    "organic_treatment": "Bacillus subtilis (QST 713 strain @ 5 ml/L) or cold-pressed Neem Oil (10,000 ppm @ 4 ml/L).",
    "prevention": "Pathogen-tested certified seed, drip fertigation, and strict 2-year non-solanaceous crop rotation.",
    "fertilizer": "Maintain balanced NPK (1:1:2); avoid excessive nitrogen which thins foliar epidermal walls.",
    "pest_control": "Control thrips and flea beetles to eliminate entry wounds.",
    "farmer_tips": "Prune bottom branches up to 15 cm above ground to eliminate soil-splash contamination.",
    "ideal_climate": "24°C - 32°C | Relative Humidity > 80%",
    "economic_threshold": "1-2 water-soaked lesions per plant canopy during vegetative stage."
  },
  "Pepper Bell Healthy": {
    "crop": "Capsicum / Bell Pepper",
    "scientific_crop": "Capsicum annuum",
    "category": "Healthy Crop",
    "pathogen": "None",
    "severity": "None",
    "status": "AI Detection Available",
    "badge": "status-healthy",
    "overview": "Optimal physiological state with vigorous foliar chlorophyll, active flowering, and firm fruit pods.",
    "etiology": "Intact palisade mesophyll, active chloroplasts, and uncompromised vascular bundles.",
    "symptoms": "Vibrant emerald green leaves, crisp margins, and firm unblemished pods.",
    "causes": "Optimal soil moisture (65-75% field capacity), soil pH 6.0-6.8, and balanced fertigation.",
    "chemical_treatment": "No corrective chemical treatment required.",
    "organic_treatment": "Bi-weekly liquid seaweed extract (2 ml/L) or humic acid drenches.",
    "prevention": "Maintain scheduled scouting and clean organic straw mulching.",
    "fertilizer": "Apply balanced water-soluble fertilizer (19:19:19 @ 3 g/L); transition to Potassium Nitrate during fruiting.",
    "pest_control": "Deploy yellow and blue sticky traps (15-20 traps/acre).",
    "farmer_tips": "Keep nighttime temperatures between 16°C and 22°C to prevent flower abortion.",
    "ideal_climate": "20°C - 28°C | Relative Humidity 55-70%",
    "economic_threshold": "N/A (Healthy Baseline)."
  },
  "Potato Early Blight": {
    "crop": "Potato",
    "scientific_crop": "Solanum tuberosum",
    "category": "Fungal Infection",
    "pathogen": "Alternaria solani",
    "severity": "Medium",
    "status": "AI Detection Available",
    "badge": "status-warning",
    "overview": "Necrotrophic fungal pathogen targeting mature foliage and causing dry, corky tuber rot.",
    "etiology": "Large, dark-colored beaked multi-celled conidia surviving in solanaceous residue and seed tubers.",
    "symptoms": "• Foliar: Dark brown circular lesions with distinct concentric target rings and yellow halos.\n• Tubers: Irregular, sunken, dark leathery lesions with brown corky flesh beneath.",
    "causes": "Alternating wet/dry foliar cycles, plant senescence, and nitrogen/potassium deficiency.",
    "chemical_treatment": "Chlorothalonil (75% WP @ 2.0 g/L) or Azoxystrobin + Difenoconazole (1.0 ml/L). PHI: 7 days.",
    "organic_treatment": "Potassium Bicarbonate (3.0 g/L) or Copper Octanoate (2.5 ml/L).",
    "prevention": "3-year crop rotation, hill up soil over tubers (10-15 cm), and avoid late-evening watering.",
    "fertilizer": "Ensure continuous Potassium and Calcium availability throughout tuber bulking.",
    "pest_control": "Control Colorado potato beetles and flea beetles.",
    "farmer_tips": "Strip infected lower yellow leaves before row closure.",
    "ideal_climate": "22°C - 30°C | Alternating wet and dry cycles",
    "economic_threshold": "5% lower canopy foliar infection observed before tuber bulking."
  },
  "Potato Late Blight": {
    "crop": "Potato",
    "scientific_crop": "Solanum tuberosum",
    "category": "Water Mold / Blight",
    "pathogen": "Phytophthora infestans",
    "severity": "Critical",
    "status": "AI Detection Available",
    "badge": "status-danger",
    "overview": "Devastating water-mold oomycete capable of collapsing potato foliage within 7-10 days and rotting stored tubers.",
    "etiology": "Biflagellate motile zoospores inside sporangia dispersed by cool, moist wind currents and rain storms.",
    "symptoms": "• Foliar: Irregular water-soaked pale-to-dark green lesions turning purplish-black with white fuzzy mold on leaf undersides in high humidity.\n• Tubers: Irregular, sunken, purplish-brown firm dry rot extending 5-15 mm into tuber flesh.",
    "causes": "Temperatures 10-21°C, relative humidity > 90%, and prolonged foliar wetness (> 8 hours).",
    "chemical_treatment": "Dimethomorph (50% WP @ 1.0 g/L), Cymoxanil + Mancozeb (2.5 g/L), or Mandipropamid (0.8 ml/L). PHI: 7 days.",
    "organic_treatment": "Preventative Bordeaux Mixture (1%) or Copper Hydroxide (2.5 g/L) before rain fronts.",
    "prevention": "Plant certified seed tubers, eradicate cull piles within 5 km, and monitor regional blight alerts.",
    "fertilizer": "Avoid excess nitrogen which produces dense, slow-drying canopies.",
    "pest_control": "Eliminate wild nightshade weed reservoirs.",
    "farmer_tips": "Desiccate (kill) vines 2 weeks prior to digging if blight is present to prevent tuber infection.",
    "ideal_climate": "10°C - 21°C | Relative Humidity > 90% | Overcast & misty",
    "economic_threshold": "Zero-tolerance. Initiate immediate treatment upon first regional diagnosis."
  },
  "Potato Healthy": {
    "crop": "Potato",
    "scientific_crop": "Solanum tuberosum",
    "category": "Healthy Crop",
    "pathogen": "None",
    "severity": "None",
    "status": "AI Detection Available",
    "badge": "status-healthy",
    "overview": "Vigorous vegetative growth, erect stems, rich compound leaves, and active subterranean tuber development.",
    "etiology": "Uncompromised vascular transport, high photosynthetic rate, and healthy root stolons.",
    "symptoms": "Uniform emerald green compound foliage, clean root stolons, and firm tuber skins.",
    "causes": "Certified virus-free seed tubers, loose sandy loam, and 65-75% soil field capacity.",
    "chemical_treatment": "No chemical treatment indicated.",
    "organic_treatment": "Glomus intraradices mycorrhizal root inoculants and foliar seaweed spray.",
    "prevention": "Hill up soil around potato stems every 2-3 weeks.",
    "fertilizer": "Apply NPK (1:2:2) at planting; Potassium Sulfate (0:0:50 @ 5 g/L) during tuber bulking.",
    "pest_control": "Inspect leaf undersides weekly for aphids.",
    "farmer_tips": "Stop nitrogen feeding 3 weeks prior to harvest for firm skin set.",
    "ideal_climate": "15°C - 22°C | Loamy, well-drained soil",
    "economic_threshold": "N/A (Healthy Baseline)."
  },
  "Tomato Early Blight": {
    "crop": "Tomato",
    "scientific_crop": "Solanum lycopersicum",
    "category": "Fungal Infection",
    "pathogen": "Alternaria linariae",
    "severity": "Medium",
    "status": "AI Detection Available",
    "badge": "status-warning",
    "overview": "Causes collar rot on seedlings, progressive lower defoliation, and sunken leathery fruit rot near the calyx.",
    "etiology": "Dark multi-septate conidia overwintering in solanaceous residue and spreading via rain splash.",
    "symptoms": "• Foliar: Concentric dark brown target rings bordered by yellow chlorotic halos.\n• Fruit: Sunken, dark leathery concentric rot lesions at stem calyx end.",
    "causes": "Warm humid conditions (24-29°C), rain splash from bare soil, and heavy fruit load stress.",
    "chemical_treatment": "Mancozeb (75% WP @ 2.5 g/L), Chlorothalonil (2.0 g/L), or Azoxystrobin (1.0 ml/L). PHI: 3 days.",
    "organic_treatment": "Bacillus subtilis (Serenade @ 3.0 g/L) and 5-8 cm organic straw mulch.",
    "prevention": "Prune lower 30 cm foliage, stake vines upright, and practice 3-year crop rotation.",
    "fertilizer": "Maintain continuous Potassium and Calcium availability.",
    "pest_control": "Control flea beetles and tomato hornworms.",
    "farmer_tips": "Strip diseased lower leaves immediately and dispose of in sealed bags.",
    "ideal_climate": "24°C - 30°C | Frequent rain / Heavy morning dew",
    "economic_threshold": "5% lower canopy foliar infection observed before first fruit harvest."
  },
  "Tomato Late Blight": {
    "crop": "Tomato",
    "scientific_crop": "Solanum lycopersicum",
    "category": "Water Mold / Blight",
    "pathogen": "Phytophthora infestans",
    "severity": "Critical",
    "status": "AI Detection Available",
    "badge": "status-danger",
    "overview": "Aggressive oomycete that rots green/ripe tomatoes into greasy bronze decay and collapses foliar canopies.",
    "etiology": "Airborne sporangia and motile zoospores spreading through cool, misty storm fronts.",
    "symptoms": "• Foliar: Water-soaked oily greenish-brown patches with white downy mold underneath.\n• Fruit: Large, firm, greasy olive-brown to bronze sunken lesions on green or ripe tomatoes.",
    "causes": "Cool, humid, overcast weather (12-22°C) with relative humidity > 90% and leaf wetness > 8 hours.",
    "chemical_treatment": "Mandipropamid (Revus @ 0.8 ml/L), Dimethomorph (1.0 g/L), or Cymoxanil + Mancozeb (2.5 g/L). PHI: 3 days.",
    "organic_treatment": "Preventative Copper Hydroxide (2.5 g/L) applied prior to forecast rain.",
    "prevention": "Plant resistant cultivars (Mountain Magic, Defiant) and water strictly at root level.",
    "fertilizer": "Avoid excess nitrogen which creates dense, slow-drying canopies.",
    "pest_control": "Eliminate wild nightshade weeds and volunteer potato patches.",
    "farmer_tips": "Harvest mature green or blushing fruit immediately before rainy storm fronts.",
    "ideal_climate": "12°C - 22°C | Relative Humidity > 90% | Overcast & misty",
    "economic_threshold": "Zero-tolerance. Initiate immediate protective spray upon regional alert."
  },
  "Tomato Bacterial Spot": {
    "crop": "Tomato",
    "scientific_crop": "Solanum lycopersicum",
    "category": "Bacterial Infection",
    "pathogen": "Xanthomonas perforans / euvesicatoria",
    "severity": "High",
    "status": "AI Detection Available",
    "badge": "status-danger",
    "overview": "Causes severe foliar necrosis, blossom drop, and raised black scab-like lesions on green and ripening tomatoes.",
    "etiology": "Gram-negative bacterium spreading via seed, splashing water, and handling wet plants.",
    "symptoms": "• Foliar: Small (under 3 mm) angular dark greasy spots with yellow halos; leaves turn brown and ragged.\n• Fruit: Small black specks enlarging into raised, rough, dark brown crater-like scabs (up to 5 mm).",
    "causes": "Driving rainstorms, overhead irrigation, temperatures 25-32°C, and relative humidity > 85%.",
    "chemical_treatment": "Copper Hydroxide (2.0 g/L) + Mancozeb (2.0 g/L) tank mix. PHI: 3 days.",
    "organic_treatment": "Bacillus subtilis (5 ml/L) or agricultural bacteriophage bio-treatments.",
    "prevention": "Use certified seed, install drip lines under plastic mulch, and disinfect stakes with bleach.",
    "fertilizer": "Maintain balanced NPK with soil pH 6.2-6.8; avoid soft vegetative growth.",
    "pest_control": "Control stink bugs and leaf-footed bugs.",
    "farmer_tips": "Stake and prune indeterminate tomatoes to keep canopy at least 30 cm above ground.",
    "ideal_climate": "25°C - 32°C | Relative Humidity > 85%",
    "economic_threshold": "First appearance of angular water-soaked leaf spots."
  },
  "Tomato Leaf Mold": {
    "crop": "Tomato",
    "scientific_crop": "Solanum lycopersicum",
    "category": "Fungal Infection",
    "pathogen": "Passalora fulva",
    "severity": "Medium",
    "status": "AI Detection Available",
    "badge": "status-warning",
    "overview": "Greenhouse and polyhouse disease favored by stagnant air and relative humidity exceeding 85%.",
    "etiology": "Branched conidiophores with pale olive conidia surviving in greenhouse framework and crop debris.",
    "symptoms": "• Foliar: Diffuse yellow patches on upper leaf surface with velvety olive-brown mold on lower surface.\n• Fruit: Blossoms abort; fruit rarely develops smooth black stem-end rot.",
    "causes": "Relative humidity > 85%, temperatures 20-25°C, and dense protected canopies.",
    "chemical_treatment": "Potassium Bicarbonate (3.0 g/L), Azoxystrobin (1.0 ml/L), or Chlorothalonil (2.0 g/L). PHI: 3 days.",
    "organic_treatment": "Bacillus amyloliquefaciens (Double Nickel @ 2.5 g/L) or horticultural mineral oil (5 ml/L).",
    "prevention": "Run greenhouse ventilation fans overnight and prune interior suckers for airflow.",
    "fertilizer": "Ensure adequate Calcium and Potash to strengthen foliar cuticles.",
    "pest_control": "Scout for whiteflies and aphids.",
    "farmer_tips": "Never overhead irrigate inside enclosed growing tunnels.",
    "ideal_climate": "20°C - 25°C | Relative Humidity > 85%",
    "economic_threshold": "Olive-green sporulation observed on > 3% of middle canopy leaves."
  },
  "Tomato Septoria Leaf Spot": {
    "crop": "Tomato",
    "scientific_crop": "Solanum lycopersicum",
    "category": "Fungal Infection",
    "pathogen": "Septoria lycopersici",
    "severity": "Medium",
    "status": "AI Detection Available",
    "badge": "status-warning",
    "overview": "Causes severe progressive lower-leaf defoliation, exposing developing tomato fruit to sunscald.",
    "etiology": "Filiform hyaline conidia extruded from dark pycnidia fruiting bodies in wet weather.",
    "symptoms": "• Foliar: Small (2-3 mm) circular spots with dark brown margins and gray centers containing black specks (pycnidia).\n• Fruit: Direct fruit lesions are rare; secondary sunscald occurs due to defoliation.",
    "causes": "Rain splash from soil debris, moderate temperatures (20-27°C), and leaf wetness > 8 hours.",
    "chemical_treatment": "Chlorothalonil (2.0 g/L), Mancozeb (2.5 g/L), or Copper Hydroxide (2.0 g/L). PHI: 3 days.",
    "organic_treatment": "Liquid Copper Octanoate (2.5 ml/L) and clean organic straw mulching.",
    "prevention": "3-year crop rotation, bottom pruning (30 cm), and drip irrigation.",
    "fertilizer": "Apply balanced compost tea to reduce defoliation stress.",
    "pest_control": "Eradicate horsenettle and groundcherry weeds.",
    "farmer_tips": "Disinfect tomato cages and stakes between growing seasons.",
    "ideal_climate": "20°C - 27°C | High rainfall / Heavy dew",
    "economic_threshold": "Spots with pycnidia on > 5% of lower canopy leaves."
  },
  "Tomato Spider Mites": {
    "crop": "Tomato",
    "scientific_crop": "Solanum lycopersicum",
    "category": "Pest Infestation",
    "pathogen": "Tetranychus urticae",
    "severity": "Medium",
    "status": "AI Detection Available",
    "badge": "status-warning",
    "overview": "Microscopic sap-sucking arachnids causing foliar stippling, chlorosis, bronzing, and silky webbing.",
    "etiology": "Rapid lifecycle (egg to adult in 5-7 days at 30°C). Overuse of pyrethroids eliminates natural predators.",
    "symptoms": "• Foliar: Fine yellow/white stippling dots across leaves; foliage turns bronze and papery with fine webs.\n• Fruit: Calyxes become webbed and fruit develops rough, pale stippled surface.",
    "causes": "Hot, dry, dusty microclimates (> 28°C), relative humidity < 50%, and drought stress.",
    "chemical_treatment": "Abamectin (1.9% EC @ 0.5 ml/L), Spiromesifen (0.8 ml/L), or Bifenazate (0.8 ml/L). PHI: 3 days.",
    "organic_treatment": "Insecticidal Soap (10 ml/L), cold-pressed Neem Oil (4 ml/L), or predatory mites.",
    "prevention": "Keep plants hydrated, dampen dusty farm paths, and preserve beneficial predatory mites.",
    "fertilizer": "Avoid high-nitrogen synthetic fertilizers which accelerate mite reproduction.",
    "pest_control": "Release predatory mites (Phytoseiulus persimilis).",
    "farmer_tips": "Spray leaf undersides thoroughly with high-pressure nozzles.",
    "ideal_climate": "> 28°C | Relative Humidity < 50% | Dusty & dry",
    "economic_threshold": "Live mites/stippling on > 10% of mid-canopy leaves."
  },
  "Tomato Target Spot": {
    "crop": "Tomato",
    "scientific_crop": "Solanum lycopersicum",
    "category": "Fungal Infection",
    "pathogen": "Corynespora cassiicola",
    "severity": "Medium",
    "status": "AI Detection Available",
    "badge": "status-warning",
    "overview": "Causes concentric brown foliar spots and circular, sunken, pitted craters directly on tomato fruit.",
    "etiology": "Large multi-septate conidia dispersed by wind and rain splash in warm, humid regions.",
    "symptoms": "• Foliar: Pinpoint brown spots expanding into circular lesions (up to 1 cm) with light centers and concentric rings.\n• Fruit: Small brown specks enlarging into sunken circular pits with dark centers.",
    "causes": "Warm temperatures (25-32°C), relative humidity > 80%, and poor canopy airflow.",
    "chemical_treatment": "Azoxystrobin (1.0 ml/L) or Chlorothalonil (2.0 g/L). PHI: 3 days.",
    "organic_treatment": "Bacillus amyloliquefaciens (Double Nickel @ 2.5 g/L) and 5-8 cm organic mulch.",
    "prevention": "Increase row spacing, stake vines, and use drip lines.",
    "fertilizer": "Ensure consistent Calcium and Potassium for fruit wall firmness.",
    "pest_control": "Control alternate weed hosts in field borders.",
    "farmer_tips": "Harvest mature fruit promptly to minimize fruit lesion exposure.",
    "ideal_climate": "25°C - 32°C | Relative Humidity > 80%",
    "economic_threshold": "Target lesions on > 5% of mid-canopy leaves during flowering."
  },
  "Tomato Yellow Leaf Curl Virus": {
    "crop": "Tomato",
    "scientific_crop": "Solanum lycopersicum",
    "category": "Viral Disease",
    "pathogen": "Tomato Yellow Leaf Curl Geminivirus (TYLCV)",
    "severity": "Critical",
    "status": "AI Detection Available",
    "badge": "status-danger",
    "overview": "Whitefly-vectored geminivirus causing severe plant stunting, upward leaf curling, and total flower drop.",
    "etiology": "Circular single-stranded DNA virus transmitted persistently by sweetpotato whiteflies (Bemisia tabaci).",
    "symptoms": "• Foliar: Severe upward curling and cupping of leaflets, interveinal chlorosis, and bushy stunted habit.\n• Fruit: Complete failure to set new fruit; existing fruit remains small, hard, and unmarketable.",
    "causes": "High populations of viruliferous whiteflies in warm, dry to sub-humid seasons.",
    "chemical_treatment": "Vector control: Imidacloprid (17.8% SL @ 0.5 ml/L) or Pymetrozine (50% WDG @ 0.6 g/L). PHI: 3 days.",
    "organic_treatment": "Beauveria bassiana (3 ml/L), Neem Oil (4 ml/L), and yellow sticky cards (25-30/acre).",
    "prevention": "Plant resistant hybrids (Tygress, Charger), install 50-mesh netting, and use silver mulch.",
    "fertilizer": "Maintain healthy organic soil conditions.",
    "pest_control": "Deploy yellow sticky traps for monitoring whiteflies.",
    "farmer_tips": "Rogue out and destroy symptomatic plants immediately.",
    "ideal_climate": "> 26°C | Abundant whitefly populations",
    "economic_threshold": "Zero-tolerance for whitefly vectors in seedling stage."
  },
  "Tomato Mosaic Virus": {
    "crop": "Tomato",
    "scientific_crop": "Solanum lycopersicum",
    "category": "Viral Disease",
    "pathogen": "Tomato Mosaic Tobamovirus (ToMV)",
    "severity": "High",
    "status": "AI Detection Available",
    "badge": "status-danger",
    "overview": "Mechanically transmitted tobamovirus causing leaf mottling, shoestring distortion, and internal fruit browning.",
    "etiology": "Rigid rod-shaped ssRNA virus surviving in dried crop residue, tools, seed coats, and tobacco products.",
    "symptoms": "• Foliar: Mottled light/dark green mosaic patterns, blistering, and 'fern-leaf' or 'shoestring' malformations.\n• Fruit: Uneven ripening, yellow blotches, and internal brown vascular necrosis in fruit walls.",
    "causes": "Physical contact with contaminated tools, hands, pruning shears, and workers using tobacco products.",
    "chemical_treatment": "No antiviral chemical exists. Infected plants must be safely removed and destroyed.",
    "organic_treatment": "Spray 20% non-fat dry milk solution on hands and tools during trellising to neutralize virus.",
    "prevention": "Plant certified resistant seed (ToMV resistant), wash hands with soap, and prohibit tobacco near fields.",
    "fertilizer": "Provide balanced organic feed to strengthen healthy neighboring plants.",
    "pest_control": "Disinfect tools with 20% non-fat dry milk solution or 10% household bleach.",
    "farmer_tips": "Always work in young, healthy blocks before visiting older blocks.",
    "ideal_climate": "Mechanical transmission through touch and tools",
    "economic_threshold": "Zero-tolerance. Rogue out symptomatic plants immediately."
  },
  "Tomato Healthy": {
    "crop": "Tomato",
    "scientific_crop": "Solanum lycopersicum",
    "category": "Healthy Crop",
    "pathogen": "None",
    "severity": "None",
    "status": "AI Detection Available",
    "badge": "status-healthy",
    "overview": "Prime physiological health with deep green foliage, robust flower trusses, and unblemished fruit.",
    "etiology": "Optimal photosynthetic efficiency, normal stomatal regulation, and uncompromised vascular flow.",
    "symptoms": "Uniform deep green foliage, crisp leaf margins, and smooth, glossy, evenly pigmented tomatoes.",
    "causes": "Loamy soil (pH 6.2-6.8), 6-8 hours daily sunlight, balanced drip fertigation, and preventative hygiene.",
    "chemical_treatment": "No corrective chemical treatment needed.",
    "organic_treatment": "Foliar kelp extract (Ascophyllum nodosum @ 2 ml/L) and humic acid drenches.",
    "prevention": "Routine sucker pruning and clean organic mulching.",
    "fertilizer": "Low-nitrogen, high-phosphorus/potassium formula (e.g., 5-10-10 or 13-0-45 @ 3 g/L) during fruiting.",
    "pest_control": "Weekly scouting for hornworms and whiteflies.",
    "farmer_tips": "Water consistently at root zone to prevent blossom end rot and fruit cracking.",
    "ideal_climate": "21°C - 28°C | 6-8 hrs daily sunlight",
    "economic_threshold": "N/A (Healthy Baseline)."
  },

  # --- BRINJAL / EGGPLANT ---
  "Brinjal Phomopsis Blight": {
    "crop": "Brinjal / Eggplant",
    "scientific_crop": "Solanum melongena",
    "category": "Fungal Infection",
    "pathogen": "Phomopsis vexans",
    "severity": "High",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-warning",
    "overview": "Destructive disease of brinjal causing collar rot on seedlings, circular foliar spots, and soft sunken fruit rot.",
    "etiology": "Fungus producing pycnidia with alpha and beta conidia. Overwinters in seed coats and infected crop residue.",
    "symptoms": "• Foliar: Circular brown leaf spots with concentric pycnidia specks.\n• Fruit: Large, sunken, soft, rotting patches with black specks making fruit mushy.",
    "causes": "Warm rainy weather (28-32°C), high humidity (> 80%), and contaminated seed lots.",
    "chemical_treatment": "Mancozeb (75% WP @ 2.5 g/L) or Carbendazim (50% WP @ 1.0 g/L) at 10-day intervals. PHI: 7 days.",
    "organic_treatment": "Hot water seed soak at 50°C for 30 minutes; Trichoderma harzianum soil treatment (5 g/L).",
    "prevention": "3-year crop rotation and complete destruction of mummified fallen fruit.",
    "fertilizer": "Apply balanced NPK (100:50:50 kg/ha); avoid excess urea.",
    "pest_control": "Control shoot and fruit borer (Leucinodes orbonalis) with Spinosad.",
    "farmer_tips": "Collect and destroy all fallen diseased fruits immediately.",
    "ideal_climate": "28°C - 32°C | High humidity and frequent rain",
    "economic_threshold": "5% fruit rot observed during first picking."
  },

  # --- CHILLI ---
  "Chilli Anthracnose / Dieback": {
    "crop": "Chilli",
    "scientific_crop": "Capsicum frutescens",
    "category": "Fungal Infection",
    "pathogen": "Colletotrichum capsici",
    "severity": "High",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-warning",
    "overview": "Causes top-downward twig drying (dieback) and sunken concentric rotting lesions on ripe chillies.",
    "etiology": "Fungus producing acervuli with black setae. Transmitted via seeds, wind-driven rain, and infected twigs.",
    "symptoms": "• Twigs: Dry straw-colored necrosis advancing downward from shoot tips.\n• Fruit: Circular sunken spots with concentric rings and pinkish spore masses on ripe pods.",
    "causes": "Warm rainy weather (28-30°C), relative humidity > 80%, and infected seeds.",
    "chemical_treatment": "Azoxystrobin (1.0 ml/L) or Copper Oxychloride (3.0 g/L) at flowering stage. PHI: 5 days.",
    "organic_treatment": "Seed treatment with Trichoderma viride (10 g/kg) and neem cake soil application.",
    "prevention": "Prune and burn dead twigs; use certified pathogen-free seeds.",
    "fertilizer": "Apply Potassium Sulfate (0:0:50) to enhance pod skin durability.",
    "pest_control": "Manage chilli thrips (Scirtothrips dorsalis) with Spinosad or Fipronil.",
    "farmer_tips": "Harvest mature ripe chillies promptly to prevent fruit rot spread.",
    "ideal_climate": "28°C - 30°C | Relative Humidity > 80%",
    "economic_threshold": "2-3% fruit lesion incidence during early fruiting."
  },

  # --- OKRA / BHINDI ---
  "Okra Yellow Vein Mosaic Virus": {
    "crop": "Okra / Lady Finger / Bhindi",
    "scientific_crop": "Abelmoschus esculentus",
    "category": "Viral Disease",
    "pathogen": "Bhendi Yellow Vein Mosaic Virus (BYVMV)",
    "severity": "Critical",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-danger",
    "overview": "Most damaging viral disease of bhindi, turning leaves yellow and rendering pods fibrous, pale, and stunted.",
    "etiology": "Begomovirus transmitted persistently by sweetpotato whiteflies (Bemisia tabaci).",
    "symptoms": "• Foliar: Network of bright yellow veins against green background; complete leaf chlorosis and stunting.\n• Pods: Small, hard, pale yellow, and fibrous unmarketable fruit.",
    "causes": "High whitefly populations in warm, humid monsoon and summer seasons.",
    "chemical_treatment": "Vector control: Acetamiprid 20% SP (0.4 g/L) or Thiamethoxam 25% WG (0.3 g/L). PHI: 5 days.",
    "organic_treatment": "Cold-pressed Neem Oil (10,000 ppm @ 4 ml/L) + Yellow sticky traps (25/acre).",
    "prevention": "Sow resistant hybrids (Arka Anamika, Parbhani Kranti); rogue out early infected plants.",
    "fertilizer": "Apply well-decomposed FYM and balanced potash.",
    "pest_control": "Install barrier crops (maize/sorghum) around okra borders to block whiteflies.",
    "farmer_tips": "Rogue out infected plants immediately to prevent whitefly vector transmission.",
    "ideal_climate": "28°C - 35°C | Abundant whitefly populations",
    "economic_threshold": "Zero-tolerance for whiteflies during vegetative growth."
  },

  # --- CUCUMBER ---
  "Cucumber Downy Mildew": {
    "crop": "Cucumber",
    "scientific_crop": "Cucumis sativus",
    "category": "Oomycete / Water Mold",
    "pathogen": "Pseudoperonospora cubensis",
    "severity": "Critical",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-danger",
    "overview": "Fast-moving foliar water mold producing distinct angular yellow lesions bounded by leaf veins.",
    "etiology": "Oomycete producing airborne sporangia that release motile zoospores on wet leaf surfaces.",
    "symptoms": "• Upper Leaf: Angular chlorotic yellow patches sharply delimited by leaf veins.\n• Lower Leaf: Dense purplish-gray downy mold sporulation directly underneath lesions.",
    "causes": "High humidity, prolonged morning dew, and overhead sprinkler irrigation.",
    "chemical_treatment": "Cymoxanil + Mancozeb (2.5 g/L) or Dimethomorph (1.0 g/L). PHI: 3 days.",
    "organic_treatment": "Copper Octanoate (2.5 ml/L) or Potassium Phosphite (2.0 ml/L).",
    "prevention": "Trellis vines for canopy aeration and install subsurface drip lines.",
    "fertilizer": "Maintain steady potassium and calcium supply to thicken cell walls.",
    "pest_control": "Scout for cucumber beetles and aphids.",
    "farmer_tips": "Spray leaf undersides thoroughly in early morning before rain fronts.",
    "ideal_climate": "18°C - 24°C | Relative Humidity > 85%",
    "economic_threshold": "Observation of angular yellow lesions on 2% of vine leaves."
  },

  # --- PUMPKIN ---
  "Pumpkin Powdery Mildew": {
    "crop": "Pumpkin",
    "scientific_crop": "Cucurbita moschata",
    "category": "Fungal Infection",
    "pathogen": "Podosphaera xanthii",
    "severity": "Medium",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-warning",
    "overview": "White talcum-powder-like fungal growth covering leaf surfaces, causing premature vine senescence.",
    "etiology": "Obligate biotrophic fungus producing chains of hyaline conidia on leaf surfaces.",
    "symptoms": "White talc-like powdery circular spots on upper/lower foliage and petioles; leaves brown and shrivel.",
    "causes": "Dry days with high relative humidity at night (20-27°C) and shaded microclimates.",
    "treatment": "Wettable Sulfur (3.0 g/L) or Difenoconazole (0.5 ml/L). PHI: 5 days.",
    "organic_treatment": "Potassium Bicarbonate (3.0 g/L) or neem oil spray (4 ml/L).",
    "prevention": "Plant in full sun, maintain wide spacing (2 x 1.5 m), and destroy old crop residue.",
    "fertilizer": "Avoid excess nitrogen which promotes soft, vulnerable foliar tissue.",
    "pest_control": "Control squash bugs and cucumber beetles.",
    "farmer_tips": "Spray milk solution (1:9 ratio with water) preventatively in home gardens.",
    "ideal_climate": "20°C - 27°C | Shaded canopy with high night humidity",
    "economic_threshold": "Powdery spots observed on > 5% of sampled crown leaves."
  },

  # --- BOTTLE GOURD / LAUKI ---
  "Bottle Gourd Anthracnose": {
    "crop": "Bottle Gourd / Lauki",
    "scientific_crop": "Lagenaria siceraria",
    "category": "Fungal Infection",
    "pathogen": "Colletotrichum orbiculare",
    "severity": "Medium",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-warning",
    "overview": "Causes water-soaked circular lesions on foliage and sunken dark lesions on elongated gourds.",
    "etiology": "Fungus producing conidia in gelatinous matrices, spread by rain splash and overhead watering.",
    "symptoms": "Circular reddish-brown foliar spots; sunken circular fruit lesions with pinkish spore tendrils.",
    "causes": "Warm wet weather (22-28°C) and water splash transmission.",
    "treatment": "Mancozeb (75% WP @ 2.5 g/L) or Copper Oxychloride (3.0 g/L). PHI: 5 days.",
    "organic_treatment": "Foliar spray of Trichoderma viride (5 g/L) and cow urine extract.",
    "prevention": "Trellis gourds on bower systems to keep fruit off moist ground.",
    "fertilizer": "Apply balanced compost tea and adequate potash.",
    "pest_control": "Manage red pumpkin beetles.",
    "farmer_tips": "Never allow developing gourds to touch wet soil.",
    "ideal_climate": "22°C - 28°C | Frequent rain splash",
    "economic_threshold": "First appearance of circular leaf lesions during flowering."
  },

  # --- BITTER GOURD / KARELA ---
  "Bitter Gourd Downy Mildew": {
    "crop": "Bitter Gourd / Karela",
    "scientific_crop": "Momordica charantia",
    "category": "Oomycete / Water Mold",
    "pathogen": "Pseudoperonospora cubensis",
    "severity": "High",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-danger",
    "overview": "Causes angular chlorotic lesions and purple-gray sporulation on bitter gourd vines.",
    "etiology": "Oomycete requiring free moisture on foliage for zoospore germination.",
    "symptoms": "Mosaic-like angular yellow lesions on leaves; purplish downy growth underneath; vine defoliation.",
    "causes": "High humidity (> 85%), prolonged rainfall, and dense vine canopies.",
    "treatment": "Metalaxyl + Mancozeb (2.5 g/L) or Cymoxanil (2.0 g/L). PHI: 5 days.",
    "organic_treatment": "Copper Octanoate (2.5 ml/L) and bower trellising.",
    "prevention": "Pandol/bower trellising and wide hill spacing (2 x 1 m).",
    "fertilizer": "Apply micronutrient spray containing Zinc and Boron.",
    "pest_control": "Deploy pheromone traps for fruit flies (Bactrocera cucurbitae).",
    "farmer_tips": "Prune lateral shoots up to 1 meter height for canopy aeration.",
    "ideal_climate": "20°C - 26°C | Relative Humidity > 85%",
    "economic_threshold": "3% foliar infection on middle canopy leaves."
  },

  # --- RIDGE GOURD / TURAI ---
  "Ridge Gourd Mosaic Virus": {
    "crop": "Ridge Gourd / Turai",
    "scientific_crop": "Luffa acutangula",
    "category": "Viral Disease",
    "pathogen": "Cucumber Mosaic Virus (CMV)",
    "severity": "High",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-danger",
    "overview": "Causes severe leaf mottling, blistering, and distorted fruit ridges in turai.",
    "etiology": "Cucumovirus transmitted non-persistently by aphids (Aphis gossypii).",
    "symptoms": "Yellow-green mosaic mottle; blistered leaves; twisted and stunted fibrous gourds.",
    "causes": "High aphid vector activity in warm weather.",
    "treatment": "Vector control: Dimethoate 30% EC (1.5 ml/L) or Neem Oil (4.0 ml/L). PHI: 5 days.",
    "organic_treatment": "Yellow sticky traps (20 traps/acre) and entomopathogenic fungi spray.",
    "prevention": "Remove volunteer cucurbit weeds and rogue out early symptomatic vines.",
    "fertilizer": "Maintain healthy organic soil biology.",
    "pest_control": "Install yellow sticky traps for monitoring aphids.",
    "farmer_tips": "Disinfect pruning scissors when trimming vines.",
    "ideal_climate": "25°C - 32°C | High aphid vector presence",
    "economic_threshold": "Zero-tolerance for aphid colonies on young shoots."
  },

  # --- SPONGE GOURD / GILKI ---
  "Sponge Gourd Gummy Stem Blight": {
    "crop": "Sponge Gourd / Gilki",
    "scientific_crop": "Luffa aegyptiaca",
    "category": "Fungal Infection",
    "pathogen": "Stagonosporopsis cucurbitacearum",
    "severity": "Medium",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-warning",
    "overview": "Causes water-soaked stem cankers that exude a gummy amber fluid, leading to vine wilt.",
    "etiology": "Fungus producing pycnidia and pseudothecia in crop debris, spreading via splash and tools.",
    "symptoms": "Brown circular leaf lesions; gummy brown liquid oozing from stem fissures; vine wilting.",
    "causes": "Warm temperatures (24-28°C), high humidity, and mechanical stem wounds.",
    "treatment": "Thiophanate-methyl (1.0 g/L) or Mancozeb (2.5 g/L). PHI: 5 days.",
    "organic_treatment": "Trichoderma viride root drench and clean straw mulching.",
    "prevention": "2-year crop rotation and clean crop residue post-harvest.",
    "fertilizer": "Ensure adequate calcium and silica to reinforce stem tissue.",
    "pest_control": "Control flea beetles and pumpkin caterpillars.",
    "farmer_tips": "Avoid stem injury during weeding operations.",
    "ideal_climate": "24°C - 28°C | High moisture retention",
    "economic_threshold": "First visual observation of amber stem gumming."
  },

  # --- POINTED GOURD / PARWAL ---
  "Pointed Gourd Collar Rot": {
    "crop": "Pointed Gourd / Parwal",
    "scientific_crop": "Trichosanthes dioica",
    "category": "Fungal Infection",
    "pathogen": "Phytophthora melonis / Rhizoctonia",
    "severity": "High",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-danger",
    "overview": "Rotting of the root-collar region at soil line causing sudden vine wilting in perennial parwal.",
    "etiology": "Soil-borne oomycete/fungus attacking vascular collar tissues under saturated conditions.",
    "symptoms": "Water-soaked dark brown collar girdling; sudden yellowing and wilting of entire vine.",
    "causes": "Waterlogging in heavy clay soils and high soil temperatures.",
    "treatment": "Soil drenching with Copper Oxychloride (3.0 g/L) or Metalaxyl (2.0 g/L). PHI: 7 days.",
    "organic_treatment": "Incorporate Trichoderma-enriched FYM at root zone at planting.",
    "prevention": "Plant on raised beds with excellent drainage channels.",
    "fertilizer": "Apply balanced FYM with neem cake.",
    "pest_control": "Scout for root-knot nematodes.",
    "farmer_tips": "Do not allow irrigation water to stagnate near vine crowns.",
    "ideal_climate": "Warm temperatures with soil water stagnation",
    "economic_threshold": "1% vine mortality observed in plot."
  },

  # --- ASH GOURD / PETHA ---
  "Ash Gourd Mosaic Virus": {
    "crop": "Ash Gourd / Petha",
    "scientific_crop": "Benincasa hispida",
    "category": "Viral Disease",
    "pathogen": "Papaya Ring Spot Virus - Cucurbit Strain",
    "severity": "Medium",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-warning",
    "overview": "Causes leaf chlorosis, puckering, and bumpy uneven fruit development in large ash gourds.",
    "etiology": "Potyvirus transmitted non-persistently by aphids.",
    "symptoms": "Interveinal yellowing, stunted leaves, and bumpy irregular fruit surface.",
    "causes": "Aphid vector transmission during early vegetative growth.",
    "treatment": "Spray Acetamiprid (0.4 g/L) for aphid management. PHI: 5 days.",
    "organic_treatment": "Neem seed kernel extract (5%) and yellow sticky traps.",
    "prevention": "Use certified virus-free seeds and plant border barrier crops.",
    "fertilizer": "Balanced basal fertilization.",
    "pest_control": "Manage aphid colonies on young leaf flushes.",
    "farmer_tips": "Rogue out infected seedlings in early nursery/vegetative stage.",
    "ideal_climate": "25°C - 32°C | High aphid activity",
    "economic_threshold": "Presence of aphid colonies on young vine tips."
  },

  # --- ZUCCHINI ---
  "Zucchini Powdery Mildew": {
    "crop": "Zucchini",
    "scientific_crop": "Cucurbita pepo",
    "category": "Fungal Infection",
    "pathogen": "Podosphaera xanthii",
    "severity": "Medium",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-warning",
    "overview": "White fungal powdery patches covering succulent zucchini leaves and petioles.",
    "etiology": "Biotrophic fungus thriving in high humidity with dry foliar surfaces.",
    "symptoms": "Powdery white circular spots expanding across leaves; leaves turn yellow and die.",
    "causes": "Warm dry days with humid nights and dense ground-level canopies.",
    "treatment": "Potassium Bicarbonate (3.0 g/L) or Azoxystrobin (1.0 ml/L). PHI: 3 days.",
    "organic_treatment": "Horticultural mineral oil (5 ml/L) or wettable sulfur (2.5 g/L).",
    "prevention": "Maintain 90 cm plant spacing for direct sunlight penetration.",
    "fertilizer": "Avoid excess nitrogen fertilizer.",
    "pest_control": "Control squash vine borers.",
    "farmer_tips": "Harvest mature zucchini every 2-3 days to maintain plant vigor.",
    "ideal_climate": "20°C - 28°C | High night humidity",
    "economic_threshold": "White spots on > 5% of older crown leaves."
  },

  # --- SNAKE GOURD / CHICHINDA ---
  "Snake Gourd Blossom End Rot": {
    "crop": "Snake Gourd / Chichinda",
    "scientific_crop": "Trichosanthes cucumerina",
    "category": "Physiological Disorder",
    "pathogen": "Calcium Deficiency / Water Stress",
    "severity": "Medium",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-warning",
    "overview": "Black, sunken leathery rot developing at the distal blossom tip of developing snake gourds.",
    "etiology": "Impaired calcium translocation to rapidly elongating distal fruit tissues during moisture stress.",
    "symptoms": "Distal tip of fruit turns water-soaked, sunken, dark brown, and leathery.",
    "causes": "Irregular watering cycles and calcium deficiency in soil.",
    "treatment": "Foliar application of Calcium Nitrate (2.5 g/L) + Boron (1.0 g/L).",
    "organic_treatment": "Apply wood ash and bone meal at root zone.",
    "prevention": "Maintain consistent drip irrigation schedules without moisture swings.",
    "fertilizer": "Ensure adequate gypsum/lime in soil prior to transplanting.",
    "pest_control": "Control melon fruit flies.",
    "farmer_tips": "Tie small stone weights to developing gourds to ensure straight downward growth.",
    "ideal_climate": "Moisture swings during rapid fruit elongation",
    "economic_threshold": "First observation of blackened fruit tips."
  },

  # --- IVY GOURD / KUNDRU ---
  "Ivy Gourd Leaf Spot": {
    "crop": "Ivy Gourd / Kundru",
    "scientific_crop": "Coccinia grandis",
    "category": "Fungal Infection",
    "pathogen": "Cercospora citrullina",
    "severity": "Low",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-warning",
    "overview": "Circular leaf spots with pale centers and dark purple margins on perennial kundru foliage.",
    "etiology": "Fungus producing septate conidia spreading via wind and water droplets.",
    "symptoms": "Small circular spots with grayish centers; heavy infection causes premature leaf yellowing.",
    "causes": "Prolonged canopy humidity and warm temperatures.",
    "treatment": "Mancozeb (2.5 g/L) or Copper Hydroxide (2.0 g/L). PHI: 5 days.",
    "organic_treatment": "Neem cake soil application and foliar bio-fungicides.",
    "prevention": "Annual pruning of old woody vines after each harvest season.",
    "fertilizer": "Apply well-decomposed FYM and balanced NPK twice annually.",
    "pest_control": "Control leaf-mining caterpillars.",
    "farmer_tips": "Prune old congested vine canopies to maintain air circulation.",
    "ideal_climate": "24°C - 30°C | Humid perennial canopy",
    "economic_threshold": "10% foliar yellowing in vine canopy."
  },

  # --- FRENCH BEAN ---
  "French Bean Rust": {
    "crop": "French Bean",
    "scientific_crop": "Phaseolus vulgaris",
    "category": "Fungal Infection",
    "pathogen": "Uromyces appendiculatus",
    "severity": "Medium",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-warning",
    "overview": "Reddish-brown powdery pustules on leaves causing premature defoliation and pod spotting.",
    "etiology": "Macrocyclic autoecious rust fungus producing urediniospores on bean foliage.",
    "symptoms": "Small raised reddish-brown powdery pustules on leaf undersides with yellow halos.",
    "causes": "Moderate temperatures (18-25°C) and relative humidity > 95%.",
    "treatment": "Wettable Sulfur (3.0 g/L) or Hexaconazole (1.0 ml/L). PHI: 7 days.",
    "organic_treatment": "Potassium Bicarbonate (3.0 g/L) or neem oil spray.",
    "prevention": "Plant rust-resistant cultivars and maintain wide row spacing.",
    "fertilizer": "Ensure adequate phosphorus and potassium; avoid excess nitrogen.",
    "pest_control": "Control bean aphids and whiteflies.",
    "farmer_tips": "Avoid touching or harvesting wet bean foliage to prevent spore spread.",
    "ideal_climate": "18°C - 25°C | Relative Humidity > 95%",
    "economic_threshold": "First visual observation of rust pustules."
  },

  # --- GREEN BEAN ---
  "Green Bean Halo Blight": {
    "crop": "Green Bean",
    "scientific_crop": "Phaseolus vulgaris var.",
    "category": "Bacterial Infection",
    "pathogen": "Pseudomonas syringae pv. phaseolicola",
    "severity": "High",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-danger",
    "overview": "Bacterial disease causing water-soaked pinpoint spots surrounded by broad yellow-green halos.",
    "etiology": "Gram-negative bacterium producing phaseolotoxin which induces systemic chlorotic halos.",
    "symptoms": "Pinpoint spots with wide greenish-yellow halos; greasy dark green spots on bean pods.",
    "causes": "Cool, rainy weather (< 22°C) and wind-blown rain.",
    "treatment": "Copper Oxychloride (3.0 g/L) or Streptocycline (0.1 g/L). PHI: 5 days.",
    "organic_treatment": "Bacillus subtilis foliar sprays and hot-water seed soaking.",
    "prevention": "Plant certified disease-free seed and practice 2-year rotation.",
    "fertilizer": "Balanced legume fertilization with Rhizobium seed inoculation.",
    "pest_control": "Control bean leaf beetles.",
    "farmer_tips": "Never irrigate with overhead sprinklers during cool cloudy periods.",
    "ideal_climate": "16°C - 22°C | Driving rainstorms",
    "economic_threshold": "First appearance of halo lesions on seedling foliage."
  },

  # --- PEAS / MATAR ---
  "Peas Powdery Mildew": {
    "crop": "Peas / Matar",
    "scientific_crop": "Pisum sativum",
    "category": "Fungal Infection",
    "pathogen": "Erysiphe pisi",
    "severity": "High",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-warning",
    "overview": "White talcum-powder-like coating over leaves, stems, and pods in cool winter weather.",
    "etiology": "Biotrophic fungus producing hyaline conidia dispersed by gentle wind currents.",
    "symptoms": "White flour-like patches spreading over entire foliage; pods turn brown and deformed.",
    "causes": "Cool dry days with humid nights (15-22°C) in late winter season.",
    "treatment": "Wettable Sulfur (3.0 g/L) or Dinocap (1.0 ml/L). PHI: 7 days.",
    "organic_treatment": "Potassium Bicarbonate (3.0 g/L) or fermented milk whey spray.",
    "prevention": "Early sowing of pea crop; use resistant varieties (Rachna, Pant Matar).",
    "fertilizer": "Apply Single Superphosphate (SSP) as basal fertilizer.",
    "pest_control": "Control pea aphids with Dimethoate.",
    "farmer_tips": "Sow early in the season to escape late-winter powdery mildew peak.",
    "ideal_climate": "15°C - 22°C | Dry days with high night humidity",
    "economic_threshold": "White powdery patches on 5% of lower canopy leaves."
  },

  # --- SWEET CORN ---
  "Sweet Corn Common Rust": {
    "crop": "Sweet Corn",
    "scientific_crop": "Zea mays var. saccharata",
    "category": "Fungal Infection",
    "pathogen": "Puccinia sorghi",
    "severity": "Medium",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-warning",
    "overview": "Golden-brown to cinnamon-brown powdery pustules across corn leaf blades.",
    "etiology": "Fungus producing urediniospores dispersed over long distances by wind.",
    "symptoms": "Small elongated brownish-red powdery pustules on upper and lower leaf surfaces.",
    "causes": "Moderate temperatures (16-25°C) and high relative humidity (> 95%).",
    "treatment": "Azoxystrobin (1.0 ml/L) or Mancozeb (2.5 g/L). PHI: 7 days.",
    "organic_treatment": "Sulfur-based fungicides applied in early vegetative stage.",
    "prevention": "Plant rust-resistant sweet corn hybrids.",
    "fertilizer": "Balanced NPK; side-dress nitrogen during knee-high stage.",
    "pest_control": "Manage fall armyworm (Spodoptera frugiperda) with Emamectin Benzoate.",
    "farmer_tips": "Scout lower whorl leaves weekly during vegetative growth.",
    "ideal_climate": "16°C - 25°C | Relative Humidity > 95%",
    "economic_threshold": "6 or more rust pustules per leaf prior to silking."
  },

  # --- CARROT ---
  "Carrot Alternaria Leaf Blight": {
    "crop": "Carrot",
    "scientific_crop": "Daucus carota",
    "category": "Fungal Infection",
    "pathogen": "Alternaria dauci",
    "severity": "Medium",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-warning",
    "overview": "Dark brown lesions with yellow halos on carrot leaflets, causing foliage to look scorched.",
    "etiology": "Necrotrophic fungus overwintering on crop debris and seed.",
    "symptoms": "Dark brown-to-black spots on leaf margins; foliage turns yellow, then brown and dies back.",
    "causes": "Prolonged leaf wetness (> 8 hours) and warm temperatures (20-28°C).",
    "treatment": "Chlorothalonil (2.0 g/L) or Difenoconazole (0.5 ml/L). PHI: 7 days.",
    "organic_treatment": "Copper Octanoate (2.5 ml/L) and hot-water seed treatment.",
    "prevention": "Wide row spacing (30-45 cm) and 3-year crop rotation.",
    "fertilizer": "Apply potassium and avoid excess nitrogen which causes hairy roots.",
    "pest_control": "Control carrot rust fly.",
    "farmer_tips": "Keep top foliage healthy to enable mechanical root pulling at harvest.",
    "ideal_climate": "20°C - 28°C | High foliar moisture",
    "economic_threshold": "10% foliar blighting observed on carrot tops."
  },

  # --- RADISH / MOOLI ---
  "Radish White Rust": {
    "crop": "Radish / Mooli",
    "scientific_crop": "Raphanus sativus",
    "category": "Oomycete / Water Mold",
    "pathogen": "Albugo candida",
    "severity": "High",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-warning",
    "overview": "White blister-like pustules on leaf undersides and swollen floral malformations.",
    "etiology": "Obligate biotrophic oomycete producing sporangia in sub-epidermal white pustules.",
    "symptoms": "Prominent chalky-white raised pustules under leaves; yellow patches on upper surface.",
    "causes": "Cool, moist weather (12-18°C) and heavy morning fog.",
    "treatment": "Metalaxyl + Mancozeb (2.5 g/L) or Copper Oxychloride (3.0 g/L). PHI: 7 days.",
    "organic_treatment": "Bordeaux Mixture (1%) and clean seed bed preparation.",
    "prevention": "Destroy cruciferous weeds (wild mustard) and practice clean cultivation.",
    "fertilizer": "Apply balanced organic manure with sulfur.",
    "pest_control": "Control flea beetles and mustard sawfly.",
    "farmer_tips": "Avoid dense sowing; thin radish seedlings to 10 cm apart.",
    "ideal_climate": "12°C - 18°C | Heavy fog / Dew",
    "economic_threshold": "White pustules observed on > 5% of leaf canopy."
  },

  # --- BEETROOT ---
  "Beetroot Cercospora Leaf Spot": {
    "crop": "Beetroot",
    "scientific_crop": "Beta vulgaris",
    "category": "Fungal Infection",
    "pathogen": "Cercospora beticola",
    "severity": "Medium",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-warning",
    "overview": "Small circular spots with tan/gray centers and distinctive reddish-purple borders.",
    "etiology": "Fungus producing needle-like conidia dispersed by rain splash and wind.",
    "symptoms": "Circular spots (2-4 mm) with gray centers and purple-red margins; leaf tearing.",
    "causes": "Warm humid conditions (25-30°C) with frequent rain or dew.",
    "treatment": "Copper Hydroxide (2.0 g/L) or Azoxystrobin (1.0 ml/L). PHI: 7 days.",
    "organic_treatment": "Bacillus subtilis foliar spray and compost mulching.",
    "prevention": "3-year crop rotation away from spinach and beets.",
    "fertilizer": "Ensure adequate Boron to prevent internal black spot (canker).",
    "pest_control": "Control leaf miners.",
    "farmer_tips": "Thin seedlings early to avoid crowded damp foliage.",
    "ideal_climate": "25°C - 30°C | Relative Humidity > 80%",
    "economic_threshold": "Spotting on > 5% of beetroot leaves."
  },

  # --- TURNIP / SHALGAM ---
  "Turnip Black Rot": {
    "crop": "Turnip / Shalgam",
    "scientific_crop": "Brassica rapa subsp. rapa",
    "category": "Bacterial Infection",
    "pathogen": "Xanthomonas campestris pv. campestris",
    "severity": "High",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-danger",
    "overview": "V-shaped yellow marginal lesions with blackened leaf veins on turnip foliage.",
    "etiology": "Bacterium entering hydathodes at leaf margins and colonizing vascular xylem.",
    "symptoms": "V-shaped chlorotic lesions with black vein networks; root vascular blackening.",
    "causes": "Warm rain splash (25-30°C) and infected seed lots.",
    "treatment": "Copper Hydroxide (2.0 g/L) + Streptocycline (0.1 g/L). PHI: 7 days.",
    "organic_treatment": "Hot water seed treatment at 50°C for 25 minutes; crop rotation.",
    "prevention": "Hot water seed soak and deep summer plowing.",
    "fertilizer": "Balanced fertilization with organic compost.",
    "pest_control": "Control cabbage butterflies.",
    "farmer_tips": "Do not enter turnip beds while foliage is wet.",
    "ideal_climate": "25°C - 30°C | Splashing rain",
    "economic_threshold": "First appearance of V-shaped marginal yellowing."
  },

  # --- CABBAGE ---
  "Cabbage Black Rot": {
    "crop": "Cabbage",
    "scientific_crop": "Brassica oleracea var. capitata",
    "category": "Bacterial Infection",
    "pathogen": "Xanthomonas campestris pv. campestris",
    "severity": "High",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-danger",
    "overview": "Bacterial vascular disease causing characteristic V-shaped yellow lesions starting from leaf edges.",
    "etiology": "Bacterium entering hydathodes, moving systemically through vascular xylem.",
    "symptoms": "V-shaped chlorotic lesions with black vein network at leaf margins; vascular blackening in stem.",
    "causes": "Infected seed, warm rains (25-30°C), and water splash through hydathodes.",
    "treatment": "Copper Hydroxide (2.0 g/L) + Streptocycline (0.1 g/L). PHI: 7 days.",
    "organic_treatment": "Hot-water seed soak at 50°C for 30 minutes; 3-year non-crucifer rotation.",
    "prevention": "Certified clean seeds and raised nursery beds.",
    "fertilizer": "Avoid excessive nitrogen which promotes soft heading tissue.",
    "pest_control": "Control diamondback moth larvae with Bacillus thuringiensis (Bt).",
    "farmer_tips": "Do not cultivate or weed field while leaves are damp.",
    "ideal_climate": "25°C - 30°C | Driving rainstorms",
    "economic_threshold": "Presence of V-shaped lesions on > 2% of plants."
  },

  # --- CAULIFLOWER ---
  "Cauliflower Downy Mildew": {
    "crop": "Cauliflower",
    "scientific_crop": "Brassica oleracea var. botrytis",
    "category": "Oomycete / Water Mold",
    "pathogen": "Hyaloperonospora parasitica",
    "severity": "High",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-warning",
    "overview": "Attacks seedlings and mature curd foliage, causing yellow spots and gray downy mold.",
    "etiology": "Oomycete producing branched conidiophores on leaf undersides in cool foggy weather.",
    "symptoms": "Yellow angular leaf spots on upper surface; white downy growth underneath; curd browning.",
    "causes": "Cool foggy weather (10-18°C) and heavy morning dew.",
    "treatment": "Metalaxyl + Mancozeb (2.5 g/L) or Dimethomorph (1.0 g/L). PHI: 7 days.",
    "organic_treatment": "Seed treatment with Trichoderma viride and Bordeaux Mixture (1%).",
    "prevention": "Nursery raised beds with excellent surface drainage.",
    "fertilizer": "Supplement with Boron (Borax @ 10 kg/ha) to prevent curd browning.",
    "pest_control": "Scout for aphids and cabbage loopers.",
    "farmer_tips": "Ensure nursery beds are not overcrowded.",
    "ideal_climate": "10°C - 18°C | Heavy morning dew",
    "economic_threshold": "Downy sporulation on > 5% of nursery seedlings."
  },

  # --- BROCCOLI ---
  "Broccoli Alternaria Black Spot": {
    "crop": "Broccoli",
    "scientific_crop": "Brassica oleracea var. italica",
    "category": "Fungal Infection",
    "pathogen": "Alternaria brassicicola",
    "severity": "Medium",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-warning",
    "overview": "Circular brown-black spots with concentric rings on broccoli leaves and dark head decay.",
    "etiology": "Fungus producing chains of dark conidia spread by rain splash and wind.",
    "symptoms": "Concentric dark brown circular spots on foliage; black pinpoint decay on green flower heads.",
    "causes": "Warm, wet weather (20-28°C) and high humidity.",
    "treatment": "Chlorothalonil (2.0 g/L) or Mancozeb (2.5 g/L). PHI: 7 days.",
    "organic_treatment": "Hot water seed soak and bio-fungicide foliar sprays.",
    "prevention": "Hot water seed soak and avoid overhead sprinkler watering.",
    "fertilizer": "Balanced NPK with adequate calcium and sulfur.",
    "pest_control": "Manage diamondback moths with Spinosad.",
    "farmer_tips": "Harvest broccoli heads in early morning when tightly packed.",
    "ideal_climate": "20°C - 28°C | High relative humidity",
    "economic_threshold": "Spotting on > 5% of head-protecting leaves."
  },

  # --- SPINACH / PALAK ---
  "Spinach Downy Mildew": {
    "crop": "Spinach / Palak",
    "scientific_crop": "Spinacia oleracea",
    "category": "Oomycete / Water Mold",
    "pathogen": "Peronospora effusa",
    "severity": "High",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-danger",
    "overview": "Causes yellow blotches on tender spinach leaves with dense purple-gray mold underneath.",
    "etiology": "Obligate biotrophic oomycete that rapidly colonizes succulent leafy mesophyll.",
    "symptoms": "Pale yellow chlorotic patches on upper foliage; violet-gray fungal fuzz underneath; leaves curl and rot.",
    "causes": "Cool, wet, humid weather (10-18°C) and dense plant stands.",
    "treatment": "Copper Octanoate (2.5 ml/L) or Potassium Phosphite (2.0 ml/L). PHI: 3 days.",
    "organic_treatment": "Bacillus subtilis spray and clean raised bed culture.",
    "prevention": "Use resistant spinach varieties, thin plants for airflow, and irrigate in early morning.",
    "fertilizer": "Apply balanced organic compost; avoid high foliar nitrogen.",
    "pest_control": "Manage leaf miners with neem formulations.",
    "farmer_tips": "Harvest uninfected leaves early if disease pressure is rising.",
    "ideal_climate": "10°C - 18°C | Dense wet canopy",
    "economic_threshold": "First appearance of violet-gray mold on leaf undersides."
  },

  # --- FENUGREEK / METHI ---
  "Fenugreek Powdery Mildew": {
    "crop": "Fenugreek / Methi",
    "scientific_crop": "Trigonella foenum-graecum",
    "category": "Fungal Infection",
    "pathogen": "Erysiphe polygoni",
    "severity": "Medium",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-warning",
    "overview": "White talc-like powdery fungal growth covering methi leaves and pods.",
    "etiology": "Biotrophic fungus thriving under cool dry conditions with high relative humidity.",
    "symptoms": "Floury white patches on upper leaf surfaces; premature leaf yellowing and shedding.",
    "causes": "Dry cool weather with high night humidity.",
    "treatment": "Wettable Sulfur (3.0 g/L) or Carbendazim (1.0 g/L). PHI: 7 days.",
    "organic_treatment": "Potassium Bicarbonate (3.0 g/L) or neem oil spray.",
    "prevention": "Early planting and avoidance of dense broadcasting.",
    "fertilizer": "Phosphorus-rich basal fertilization.",
    "pest_control": "Control aphids with soap spray.",
    "farmer_tips": "Harvest green leaves at 30-35 days before powdery mildew onset.",
    "ideal_climate": "15°C - 22°C | Dry days with humid nights",
    "economic_threshold": "White powdery spots on > 5% of methi foliage."
  },

  # --- CORIANDER / DHANIYA ---
  "Coriander Stem Gall": {
    "crop": "Coriander / Dhaniya",
    "scientific_crop": "Coriandrum sativum",
    "category": "Fungal Infection",
    "pathogen": "Protomyces macrosporus",
    "severity": "High",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-warning",
    "overview": "Tumor-like gall swellings on coriander stems, leaves, and seed umbels.",
    "etiology": "Fungus producing resting chlamydospores inside hypertrophied host tissues.",
    "symptoms": "Swollen blister-like galls on stems, leaf veins, and seeds; distorted seed shape.",
    "causes": "Excess soil moisture and high winter humidity.",
    "treatment": "Hexaconazole (1.0 ml/L) or Copper Oxychloride (3.0 g/L). PHI: 7 days.",
    "organic_treatment": "Seed treatment with Trichoderma (10 g/kg) and solarization.",
    "prevention": "Seed treatment with Thiram (2.5 g/kg) and light, frequent irrigations.",
    "fertilizer": "Balanced compost; avoid excessive watering.",
    "pest_control": "Control coriander aphids.",
    "farmer_tips": "Avoid heavy waterlogged soils for coriander cultivation.",
    "ideal_climate": "Cool weather with excessive soil moisture",
    "economic_threshold": "Observation of first stem swellings."
  },

  # --- LETTUCE ---
  "Lettuce Bottom Rot": {
    "crop": "Lettuce",
    "scientific_crop": "Lactuca sativa",
    "category": "Fungal Infection",
    "pathogen": "Rhizoctonia solani",
    "severity": "High",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-danger",
    "overview": "Rotting of lower leaves touching damp soil, progressing into complete head collapse.",
    "etiology": "Soil-borne fungus producing sclerotia that infect lower leaf midribs touching soil.",
    "symptoms": "Sunken brown lesions on lower leaf midribs; leaves turn slimy, brown, and rot completely.",
    "causes": "Warm, wet soils (> 20°C) and poor bed drainage.",
    "treatment": "Azoxystrobin (1.0 ml/L) or Iprodione (1.5 g/L). PHI: 5 days.",
    "organic_treatment": "Trichoderma soil application and straw mulching.",
    "prevention": "Plant on high raised beds covered with plastic or straw mulch.",
    "fertilizer": "Balanced nutrition with good drainage.",
    "pest_control": "Control slugs and snails.",
    "farmer_tips": "Keep lettuce heads elevated above wet soil.",
    "ideal_climate": "> 20°C | Saturated soil surface",
    "economic_threshold": "1-2% head rot observed in bed."
  },

  # --- AMARANTH / CHAULAI ---
  "Amaranth White Rust": {
    "crop": "Amaranth / Chaulai",
    "scientific_crop": "Amaranthus cruentus",
    "category": "Oomycete / Water Mold",
    "pathogen": "Albugo bliti",
    "severity": "Medium",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-warning",
    "overview": "Chalky-white blister-like pustules on the lower surface of chaulai foliage.",
    "etiology": "Oomycete producing sub-epidermal sporangial pustules.",
    "symptoms": "White pustules on leaf undersides; corresponding upper leaf shows yellow spots.",
    "causes": "Warm humid conditions (22-30°C) and heavy morning dew.",
    "treatment": "Copper Oxychloride (3.0 g/L) or Mancozeb (2.5 g/L). PHI: 5 days.",
    "organic_treatment": "Neem oil spray (4 ml/L) and crop thinning.",
    "prevention": "Thin plants to allow good air movement and harvest young tender shoots.",
    "fertilizer": "Apply farmyard manure and light nitrogen after each cutting.",
    "pest_control": "Control leaf webbers.",
    "farmer_tips": "Harvest shoots frequently to prevent disease buildup.",
    "ideal_climate": "22°C - 30°C | High relative humidity",
    "economic_threshold": "White pustules on > 5% of harvested greens."
  },

  # --- ONION ---
  "Onion Purple Blotch": {
    "crop": "Onion",
    "scientific_crop": "Allium cepa",
    "category": "Fungal Infection",
    "pathogen": "Alternaria porri",
    "severity": "High",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-warning",
    "overview": "Causes sunken purple lesions on onion leaves and flower stalks, leading to premature leaf collapse.",
    "etiology": "Fungus producing large dark conidia spread by rain splash and wind.",
    "symptoms": "Small water-soaked spots developing purple-brown centers with yellow halos; leaf tips die back.",
    "causes": "Warm humid weather (25-30°C), heavy dew, and thrips injury.",
    "treatment": "Mancozeb (2.5 g/L) or Tebuconazole (1.0 ml/L) with non-ionic sticker. PHI: 7 days.",
    "organic_treatment": "Foliar spray of Trichoderma viride and neem oil.",
    "prevention": "Good soil drainage, certified seed bulbs, and 3-year crop rotation.",
    "fertilizer": "Apply balanced sulfur and potassium for bulb skin durability.",
    "pest_control": "Control onion thrips (Thrips tabaci) with Fipronil (1.5 ml/L).",
    "farmer_tips": "Always add a surfactant/spreader to sprays because onion leaves have waxy cuticles.",
    "ideal_climate": "25°C - 30°C | Heavy dew & thrips infestation",
    "economic_threshold": "Purple spots on > 5% of standing onion leaves."
  },

  # --- GARLIC ---
  "Garlic Rust": {
    "crop": "Garlic",
    "scientific_crop": "Allium sativum",
    "category": "Fungal Infection",
    "pathogen": "Puccinia allii",
    "severity": "Medium",
    "status": "Knowledge Available / Training Planned",
    "badge": "status-warning",
    "overview": "Bright orange-to-yellow raised powdery pustules covering garlic leaves.",
    "etiology": "Autoecious rust fungus producing yellow urediniospores.",
    "symptoms": "Small white flecks turning into raised bright orange/yellow powdery blisters; leaves die back.",
    "causes": "High relative humidity (100%) and moderate temperatures (12-20°C).",
    "treatment": "Tebuconazole (1.0 ml/L) or Mancozeb (2.5 g/L) + non-ionic surfactant. PHI: 7 days.",
    "organic_treatment": "Sulfur-based fungicides and bulb treatment.",
    "prevention": "Plant certified clean garlic cloves and avoid excess nitrogen.",
    "fertilizer": "Ensure adequate sulfur and potash for bulb hardness.",
    "pest_control": "Manage onion thrips.",
    "farmer_tips": "Stop all irrigation 20 days prior to harvest to prevent bulb rot.",
    "ideal_climate": "12°C - 20°C | Relative Humidity > 90%",
    "economic_threshold": "Rust pustules observed on > 5% of garlic foliage."
  }
}

# 3. WRITE ALL JSON DATABASES SAFELY
files_map = {
    DATA_DIR / "plant_database.json": PLANT_DATABASE,
    DATA_DIR / "diseases.json": DISEASE_DATABASE
}

for file_path, data in files_map.items():
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"Generated: {file_path}")

print(f"\nAll 35 crop pathology databases successfully written to {DATA_DIR}!")
